<html>
<head>
<?php
echo '<title>Hello from ADK-Linux Server!</title>';
?>
</head>
<body>
<?php
       echo '<p>This content was generated by PHP on ADK-Linux Server</p>';
?>
<p>And this content is static HTML on ADK-Linux Server</p>
</body>
</html>
